name: mydotnet project

on:
  push:
    branches:
      - develop

jobs:
  dotnet_publish:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.416'

      - name: Restore dependencies
        run: dotnet restore src/Presentation/Nop.Web/Nop.Web.csproj

      - name: Publish .NET project
        run: dotnet publish -c Release src/Presentation/Nop.Web/Nop.Web.csproj -o demo
