name: mydotnet pname: mydotnet project

on:
  push:
    branches:
      - develop

jobs:
  dotnet_publish:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.203'

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: SonarCloud Begin Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin \
            /k:"charan-09-08_nopCommerce" \
            /o:"charan" \
            /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Build
        run: dotnet build -c Release src/Presentation/Nop.Web/Nop.Web.csproj --no-incremental

      - name: End SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Publish
        run: dotnet publish -c Release src/Presentation/Nop.Web/Nop.Web.csproj -o demo
